version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ../country-api-middleware  # Point to your backend directory
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=1d
    volumes:
      - backend-db:/usr/src/app/database.sqlite

volumes:
  backend-db: