version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=1d
    volumes:
      - ./database.sqlite:/usr/src/app/database.sqlite
      - /usr/src/app/node_modules
    restart: unless-stopped